### ISSUE TITLE
Proper metrics logging for redraw Perfmon graphs from results..

### ISSUE THREAD

**Issue by ruthan** [undera/perfmon-agent#12]
For years its Perfmon logging sort of hack, which is using standard Jmeter jtl logging, header is wrong, it would be nice to finally fix it and log proper header is style of
 Host/IP-Metric collect - Metric parametr..
so finall log could look like..
Jmeter timestamp;  Host/IP1-Metric collect1-MetricParameter1;Host/IP1-Metric collect2-MetricParameter1; Host/IP2-MetrictCollect1-MetricParameter1

 And there should be browse Browse button on Perfmon Metrics Collector to load these logs.. and redrawn graph from them.. as its possible for other Listeners.

**Comment by undera** [comment]
This is not issue of Agent, it's PerMon client issue

**Comment by ruthan** [comment]
Ok, so could you move issue to proper category?

**Comment by undera** [comment]
No, I can't move it. There is no "move" action on GitHub and there's no issue tracker on the destination project. Your only option is to discuss this issue on project mailing list.
