### ISSUE TITLE
CMDRunner error

### ISSUE THREAD

**Issue by AliAlican** [undera/perfmon-agent#19]
I uploaded the plugin to aws ec2 instance but when i run it i get CMDRunner.jar not found error.

Should i install it to server somehow, how should i install it?

**Comment by undera** [comment]
How do you run it?

**Comment by AliAlican** [comment]
![image](https://user-images.githubusercontent.com/44370554/114547323-996f5000-9c5e-11eb-9a69-4ed8da18d3ba.png)
Here

**Comment by undera** [comment]
You need to download the release ZIP, not source code.

**Comment by AliAlican** [comment]
Lol thanks a lot, I didn't know that. Works perfectly now.
