### ISSUE TITLE
 A fatal error : EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by dipakkumar1225** [undera/perfmon-agent#20]
OS: Windows 10
JAVA: 14
![image](https://user-images.githubusercontent.com/46619348/120593419-19df4f80-c45d-11eb-81cc-78a1bade0e12.png)

**Comment by undera** [comment]
This is a problem of underlying SIGAR library, which is old and unmaintained. Perfmon Agent can't do anything with that, sorry.

**Comment by dipakkumar1225** [comment]
I am able to run after following the steps that was mentioned in Installation section.
1. Created JRE folder under the extracted agent folder.
2. Copy JRE from Android studio which comes with 1.8
3. Change the java command inside startAgent.bat file to the path to the java executable.

On console below are the error which I am getting now. 
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
