### ISSUE TITLE
Using param "usedperc" from metric memory

### ISSUE THREAD

**Issue by willyamcts** [undera/perfmon-agent#21]
The "usedperc" parameter is the default for the memory metric, but it doesn't always work correctly.

Eventually the X10 multiplication value appears next to the legend, which makes the value incomprehensible, as it does not correspond to the percentage of use of memory or even the amount of memory in use in B, MB or GB.

In case below, the usage of memory was in 4-6% (~300MB of usage total) but the value show does not match consumption.
![image](https://user-images.githubusercontent.com/20804939/122563574-bd625f80-d01a-11eb-92e8-3f8feb3ede11.png)

Note explicity param "usedperc"

**Comment by undera** [comment]
That's not perfmon agent problem, it's plugin that displays it.
If consumption was around 5%, then 5*10=50, which matches what is displayed on picture.
