### ISSUE TITLE
Java version compatibility of ServerAgent 2.2.3

### ISSUE THREAD

**Issue by swamipasam** [undera/perfmon-agent#24]
It seems with ServerAgent 2.2.3 is working fine with jdk1.8.0_231, but not with jdk1.8.0_301, and also with higher version jdk-17.0.1. 

Just waned to bring it your notice, at least all sub version of jdk 1.8 would have worked. Here is log file for  jdk1.8.0_301 👍 

[hs_err_pid2124.log](https://github.com/undera/perfmon-agent/files/7587067/hs_err_pid2124.log)

I switched back to jdk1.8.0_231, and for now its not an urgent issue for me, but just wanted to report here.

**Comment by andresoviedo** [comment]
Hello there.  Thank you for your feedback.  I have the same issue here.  

Not working on Windows 10 x64 with neither jdk8u292-b10 nor jdk-11.0.15+10 nor jdk Corretto-8.332.08.1

It works however with **jre1.8.0_211**

**Comment by undera** [comment]
Thanks for sharing your issue.
Server Agent uses "SIGAR" library to gather system metrics. That library is not maintained for a long time, thus ServerAgent can't really do much about it.
