### ISSUE TITLE
Serveragent took too much CPU

### ISSUE THREAD

**Issue by lishuoluke** [undera/perfmon-agent#9]

**Comment by lishuoluke** [comment]
I install serveragent on a machine and monitor the performance but somehow I observed that the serveragent itself occupy 44% of the CPU!


 9639 root      20   0 4592680  40468  16692 S  43.5  0.1   4:29.71 java -Xms1024m -Xmx2048m -jar ./CMDRunner.jar --tool PerfMonAgent --udp-port 1983 --tcp-port 1983

Did I make any mistake? thank you for help!

**Comment by undera** [comment]
We can't do anything about its CPU usage. Because it is caused by underlying SIGAR library.
It was reported by users in the past that on some machines this problem occur.

**Comment by lishuoluke** [comment]
Hi undera,

Thank you for the response.
I figure out what happened, I use the watcher to track number of TCP alive connections in the  server and it takes lots of CPU for resolve the domain name. Once I remove the TCP watcher, the CPU usage dropped below 1% .  Hope this information is useful for you!

Regards,
Luke
